# -*- coding: utf-8 -*-
"""Dashboard cacao y chontaduro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SuVNZ1_Q9CRrpU7FrRpQ2SUY7UCHpG9d
"""

import pandas as pd

# Cargar archivo
file_path = "Cultivos_permanentes.xlsx"
xls = pd.ExcelFile(file_path)

# Mostrar nombres de las hojas
sheet_names = xls.sheet_names
sheet_names

# Cargar la hoja principal
df = xls.parse('2000-2023')

# Mostrar las primeras filas para examinar la estructura
df.head()

# Filtrar solo los cultivos de interés: cacao y chontaduro
df_filtrado = df[df['Cultivo'].str.lower().isin(['cacao', 'chontaduro'])]

# Agrupar por Año y Cultivo, sumar las métricas relevantes
df_agrupado = df_filtrado.groupby(['Año', 'Cultivo'], as_index=False).agg({
    'Hectareas_sembradas': 'sum',
    'Hectareas_cosechadas': 'sum',
    'Produccion_toneladas': 'sum',
    'Rendimiento_toneladas/hectareas': 'mean'
})

import matplotlib.pyplot as plt

# Crear las gráficas
cultivos = df_agrupado['Cultivo'].unique()
metricas = {
    'Hectareas_sembradas': 'Hectáreas sembradas',
    'Hectareas_cosechadas': 'Hectáreas cosechadas',
    'Produccion_toneladas': 'Producción (toneladas)',
    'Rendimiento_toneladas/hectareas': 'Rendimiento (toneladas/ha)'
}

for metrica, titulo in metricas.items():
    plt.figure(figsize=(10, 5))
    for cultivo in cultivos:
        data = df_agrupado[df_agrupado['Cultivo'] == cultivo]
        plt.plot(data['Año'], data[metrica], marker='o', label=cultivo)
    plt.title(f'{titulo} a través del tiempo')
    plt.xlabel('Año')
    plt.ylabel(titulo)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# Cargar archivo
precio_path = "Historicocao.xlsx"
precio_df = pd.read_excel(precio_path)

# Mostrar las primeras filas para entender la estructura
precio_df.head()

# Limpiar y convertir datos
precio_df['Fecha'] = pd.to_datetime(precio_df['Fecha'])
precio_df['Apertura'] = pd.to_numeric(precio_df['Apertura'], errors='coerce')
precio_df['% var.'] = precio_df['% var.'].str.replace('%', '').str.replace(',', '.')
precio_df['% var.'] = pd.to_numeric(precio_df['% var.'], errors='coerce')

# Ordenar por fecha
precio_df = precio_df.sort_values('Fecha')

# Graficar precio de apertura y % variación
import matplotlib.pyplot as plt

fig, ax1 = plt.subplots(figsize=(12, 5))

# Línea de apertura
ax1.plot(precio_df['Fecha'], precio_df['Apertura'], color='blue', marker='o', label='Precio de Apertura')
ax1.set_xlabel('Fecha')
ax1.set_ylabel('Precio de Apertura (USD)', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')

# Segundo eje para % var
ax2 = ax1.twinx()
ax2.plot(precio_df['Fecha'], precio_df['% var.'], color='green', marker='s', linestyle='--', label='% Variación')
ax2.set_ylabel('% Variación Diaria', color='green')
ax2.tick_params(axis='y', labelcolor='green')

# Título y formato
plt.title('Precio de Apertura y % de Variación - Cacao')
fig.tight_layout()
plt.grid(True)
plt.show()